# Generated by Django 4.2.16 on 2024-09-18 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bouquet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='название букета')),
                ('description', models.TextField(blank=True, verbose_name='описание букета')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='', verbose_name='изображение букета')),
                ('price', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Цена букета')),
                ('recomend', models.BooleanField(default=False, verbose_name='рекомендуемый торт')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='Событие')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, verbose_name='комментарий к заказу')),
                ('address', models.TextField(help_text='ул. Подольских курсантов д.5 кв.4', verbose_name='Адрес квартиры')),
                ('order_price', models.FloatField(blank=True, null=True, verbose_name='Сумма заказа')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='время создания')),
                ('delivery_date', models.DateField(blank=True, verbose_name='дата доставки')),
                ('delivery_time', models.CharField(blank=True, choices=[('01', 'Как можно скорее'), ('02', '10:00-12:00'), ('03', '12:00-14:00'), ('04', '14:00-16:00'), ('05', '16:00-18:00'), ('06', '18:00-20:00')], max_length=2, verbose_name='время доставки')),
                ('order_status', models.CharField(choices=[('01', 'Оформлен'), ('02', 'Оплачен'), ('03', 'В доставке'), ('04', 'Доставлен')], default='01', max_length=2, verbose_name='статус заказа')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('phone', models.CharField(max_length=12, unique=True, verbose_name='Телефон')),
                ('tm_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='ID Телеграм')),
                ('role', models.CharField(choices=[('01', 'Клиент'), ('02', 'Курьер'), ('03', 'Флорист')], default='01', max_length=2, verbose_name='статус персоны')),
            ],
        ),
        migrations.CreateModel(
            name='Price_range',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_min', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Цена минимум')),
                ('price_max', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Цена максимум')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=12, unique=True, verbose_name='Телефон магазина')),
                ('address', models.TextField(help_text='ул. Подольских курсантов д.5 кв.4', verbose_name='Адрес магазина')),
            ],
        ),
        migrations.CreateModel(
            name='OrderedBouquet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Количество букетов')),
                ('bouquet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordered_bouquets', to='shop.bouquet', verbose_name='букеты')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordered_cakes', to='shop.order', verbose_name='заказы')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='bouquet',
            field=models.ManyToManyField(related_name='orders', through='shop.OrderedBouquet', to='shop.bouquet', verbose_name='букеты'),
        ),
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='shop.person', verbose_name='клиент'),
        ),
        migrations.AddField(
            model_name='bouquet',
            name='events',
            field=models.ManyToManyField(related_name='bouquets', to='shop.event', verbose_name='события'),
        ),
    ]
