# Generated by Django 4.2.16 on 2024-09-19 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bouquet',
            name='recomend',
            field=models.BooleanField(default=False, verbose_name='рекомендуемый букет'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_price',
            field=models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Сумма заказа'),
        ),
        migrations.AlterField(
            model_name='orderedbouquet',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordered_bouquets', to='shop.order', verbose_name='заказы'),
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='время создания')),
                ('consultation_status', models.CharField(choices=[('01', 'Оформлена'), ('02', 'Обработана')], default='01', max_length=2, verbose_name='статус консультации')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to='shop.person', verbose_name='клиент')),
            ],
        ),
    ]
