# Generated by Django 4.2.16 on 2024-09-19 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_bouquet_recomend_alter_order_order_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bouquet',
            name='composition',
            field=models.TextField(blank=True, verbose_name='состав букета'),
        ),
        migrations.AddField(
            model_name='bouquet',
            name='size',
            field=models.TextField(blank=True, verbose_name='размер букета'),
        ),
    ]
