# Generated by Django 5.1.1 on 2024-09-21 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_consultationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationrequest',
            name='is_closed',
            field=models.BooleanField(default='False', verbose_name='Обработана?'),
        ),
    ]
