# Generated by Django 5.1.1 on 2024-09-21 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_person_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='bouquet',
        ),
        migrations.AddField(
            model_name='order',
            name='bouquet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='shop.bouquet', verbose_name='букет'),
        ),
    ]
