# Generated by Django 5.1.1 on 2024-09-22 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_remove_order_bouquet_order_bouquet'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationrequest',
            name='message_id',
            field=models.CharField(blank=True, max_length=25, verbose_name='Ключ сообщения телеграмм'),
        ),
    ]
