# Generated by Django 5.1.1 on 2024-09-23 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_order_delivery_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultationrequest',
            name='message_id',
        ),
    ]
