# Generated by Django 4.2.16 on 2024-09-18 14:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bouquet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название букета')),
                ('description', models.CharField(max_length=100, verbose_name='Описание букета')),
                ('size', models.CharField(max_length=100, verbose_name='Описание размеров')),
                ('price', models.IntegerField(verbose_name='Цена в руб.')),
            ],
            options={
                'verbose_name': 'букет',
                'verbose_name_plural': 'букеты',
            },
        ),
        migrations.CreateModel(
            name='Occasion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование причины')),
            ],
            options={
                'verbose_name': 'причина',
                'verbose_name_plural': 'причины',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('telegram_id', models.CharField(max_length=100, verbose_name='id в телеграме')),
                ('role', models.CharField(choices=[('customer', 'Покупатель'), ('courier', 'Курьер'), ('florist', 'Флорист')], default='customer', max_length=15, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'человек',
                'verbose_name_plural': 'люди',
            },
        ),
        migrations.CreateModel(
            name='Price_range',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('low', models.IntegerField(default=0, verbose_name='Нижняя граница')),
                ('high', models.IntegerField(default=0, verbose_name='Верхняя граница')),
            ],
            options={
                'verbose_name': 'бюджет',
                'verbose_name_plural': 'бюджеты',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'магазин',
                'verbose_name_plural': 'магазины',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Дата и время заказа')),
                ('status', models.CharField(choices=[('created', 'Создан'), ('paid', 'Оплачен'), ('processed', 'Собран'), ('being_delivered', 'Передан в доставку')], default='created', max_length=20)),
                ('address', models.CharField(max_length=100, verbose_name='Адрес доставки')),
                ('delivery_time', models.TimeField(verbose_name='Время доставки')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('commentary', models.TextField(verbose_name='Комментарии к заказу')),
                ('bouquet', models.ManyToManyField(blank=True, related_name='orders', to='flower_store.bouquet', verbose_name='Букет')),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Courier', to='flower_store.person', verbose_name='Курьер')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Customer', to='flower_store.person', verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
            },
        ),
        migrations.AddField(
            model_name='bouquet',
            name='occasion',
            field=models.ManyToManyField(blank=True, related_name='bouquets', to='flower_store.occasion', verbose_name='Событие'),
        ),
    ]
